languageCode = "en"
title = "Pi Society"
theme = "pisoc-minimal"
pluralizelisttitles = "false"

[params]
    githubUsername = "pisoc"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["python", "go"]

[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url = "/news"
    name = "news"
    weight = 2

[[menu.main]]
    url = "/events"
    name = "events"
    weight = 3

[[menu.main]]
    url = "/projects"
    name = "projects"
    weight = 4

[[menu.main]]
    url = "/minutes"
    name = "minutes"
    weight = 5

[[menu.main]]
    url = "/random"
    name = "random"
    weight = 6

[[menu.main]]
    url = "/contact"
    name = "contact"
    weight = 7

[[menu.main]]
    url = "/meetings"
    name = "meetings"
    weight = 8

[[menu.main]]
    url = "http://www.bradfordunisu.co.uk/groups/pi-society-pisoc/join"
    name = "join"
    weight = 9

[[menu.main]]
    url = "https://github.com/pisoc"
    name = "github"
    weight = 10

# [[menu.main]]
#     url = "https://www.facebook.com/groups/ubupisoc"
#     name = "facebook"
#     weight = 11

# [[menu.main]]
#     url = "mailto:pisoc@ubu.bradford.ac.uk"
#     name = "email"
#     weight = 12

[[menu.main]]
    url = "/picon-2020"
    name = "picon"
    weight = 12

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
