os: linux
dist: xenial
language: minimal

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.44/hugo_0.44_Linux-64bit.deb
  - sudo dpkg -i hugo_0.44_Linux-64bit.deb

script:
  - hugo
  - echo 'pisoc.net' > public/CNAME # Keep github pages happy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  repo: pisoc/pisoc.github.io
  target_branch: master
  on:
    branch: master

notifications:
  webhooks: http://hooks.pisoc.net:8080/travis-ci

# after_script:
#   - curl -X POST https://api.telegram.org/bot$PISOCBOT_TOKEN/sendMessage
#     -d chat_id=$TG_CHAT_ID
#     -d "text=CI/CD passed for pisoc.net"