os: linux
dist: xenial
language: minimal

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.44/hugo_0.44_Linux-64bit.deb
  - sudo dpkg -i hugo_0.44_Linux-64bit.deb

script:
  - hugo

