os: linux
dist: xenial
language: minimal

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.44/hugo_0.44_Linux-64bit.deb
  - sudo dpkg -i hugo_0.44_Linux-64bit.deb

script:
  - hugo
  # Keep github pages happy
  - echo 'pisoc.net' > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  repo: pisoc/pisoc.github.io
  target_branch: master
  on:
    branch: master
